Feature/somewhat improved frontend
Supergamer1337/sIT pull request #8
Opened 2023-04-18 12:37 UTC by x183

is bootiful :rose:

2023-04-26 09:01 UTC, Supergamer1337 requested changes
Some questions, and a suggestion

2023-07-20 16:10 UTC, x183 commented on frontend/components/Search/Search.tsx
> +            amount: 20 /* document.body.clientHeight / 50 */,
No

2023-07-23 12:06 UTC, Supergamer1337 commented on frontend/components/Search/Search.tsx
> +            amount: 20 /* document.body.clientHeight / 50 */,
Leave a comment explaining why that is then

2023-07-25 07:00 UTC, Supergamer1337 approved these changes
LGTM

2023-07-25 07:30 UTC, merged